# Generated by Django 5.0.6 on 2025-06-21 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopsim', '0003_alter_pricequote_icms_credit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icms_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pis_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cofins_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('item_icms_excluded', models.BooleanField(default=False)),
                ('items_pis_cofins_excluded', models.BooleanField(default=False)),
                ('markup', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('card_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='pricing.itemclass')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='shopsim.supplierprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
