# Generated by Django 5.0.6 on 2025-06-21 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricing_total_cost_at_moment_costsmaster_userscosts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costsdetail',
            name='user_costs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_costs_detail', to='pricing.userscosts'),
        ),
    ]
