# Generated by Django 5.0.6 on 2025-06-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_costsdetail_user_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='total_cost_at_moment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
