# Generated by Django 5.0.6 on 2025-07-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_costs_created_at_costs_updated_at_states_created_at_and_more'),
        ('pricing', '0004_alter_pricing_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='item_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='state_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_option', to='base.states', verbose_name='State Option'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='tax_icms_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
