# Generated by Django 5.0.6 on 2025-07-12 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_pricing_item_description_pricing_state_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='item_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='pricing.itemclass'),
        ),
    ]
