# Generated by Django 5.0.6 on 2025-07-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_pricing_item_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='operational_cost_percentage_display',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
