# Generated by Django 5.0.6 on 2024-05-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ERPModel',
            new_name='ERP',
        ),
    ]
