# Generated by Django 5.0.6 on 2024-07-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_erp_unnecessary_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erp',
            name='unnecessary_fields',
        ),
    ]
