# Generated by Django 5.0.6 on 2025-07-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_accessdropbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPIntegrationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='erp',
            name='method_integration',
            field=models.CharField(blank=True, choices=[('1', 'API'), ('2', 'FTP'), ('3', 'SFTP'), ('4', 'Manual')], max_length=2, null=True),
        ),
    ]
