# Generated by Django 5.0.6 on 2025-07-21 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_erpintegrationschedule_erp_method_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='erp',
            name='periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.erpintegrationschedule'),
        ),
    ]
