# Generated by Django 5.0.6 on 2025-08-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_erp_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='erp',
            name='use_float_redbc',
            field=models.BooleanField(default=False, help_text='Use float for redbcde and redbcpara fields'),
        ),
    ]
