# Generated by Django 5.0.6 on 2024-09-02 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0019_alter_client_token'),
        ('impostos', '0016_cbenef_legislation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedItemTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('sequencial', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('barcode', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('ncm', models.CharField(max_length=255)),
                ('cest', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cfop', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('icms_cst', models.IntegerField(blank=True, default=0, null=True)),
                ('icms_aliquota', models.IntegerField(blank=True, default=0, null=True)),
                ('icms_aliquota_reduzida', models.IntegerField(blank=True, default=0, null=True)),
                ('protege', models.IntegerField(blank=True, default=0, null=True)),
                ('cbenef', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('piscofins_cst', models.IntegerField(blank=True, default=0, null=True)),
                ('pis_aliquota', models.FloatField(blank=True, default=0, null=True)),
                ('cofins_aliquota', models.FloatField(blank=True, default=0, null=True)),
                ('naturezareceita', models.IntegerField(blank=True, default=0, null=True)),
                ('status_item', models.IntegerField(choices=[(0, 'Produto Novo'), (1, 'Problemas Encontrados')], default=1)),
                ('is_pending', models.BooleanField(default=True)),
                ('divergent_columns', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('estado_origem', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('estado_destino', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('sequencial', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('barcode', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('ncm', models.CharField(max_length=8)),
                ('cest', models.CharField(blank=True, default='', max_length=7, null=True)),
                ('icms_aliquota_reduzida', models.CharField(max_length=3)),
                ('pis_aliquota', models.FloatField()),
                ('cofins_aliquota', models.FloatField()),
                ('type_product', models.CharField(blank=True, choices=[('', '----'), ('Revenda', 'Revenda'), ('Imobilizado', 'Imobilizado'), ('Insumos', 'Insumos')], default='', max_length=20)),
                ('other_information', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status_item', models.IntegerField(choices=[(0, 'Produto Novo'), (1, 'Aguardando Sincronização'), (2, 'Enviado - Aguard Validação'), (3, 'Validado')], default=3)),
                ('history', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('estado_origem', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('estado_destino', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pending_sync', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sync_at', models.DateTimeField(blank=True, null=True)),
                ('await_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_validate_at', models.DateTimeField(blank=True, null=True)),
                ('cbenef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='impostos.cbenef')),
                ('cfop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='impostos.cfop')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client')),
                ('icms_aliquota', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='impostos.icmsaliquota')),
                ('icms_cst', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='impostos.icmscst')),
                ('naturezareceita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='impostos.naturezareceita')),
                ('piscofins_cst', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='piscofins_cst_items_teste', to='impostos.piscofinscst')),
                ('protege', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='impostos.protege')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_created_teste', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_updated_teste', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='itemtest',
            constraint=models.UniqueConstraint(fields=('client', 'code'), name='unique_client_code_teste'),
        ),
    ]
