# Generated by Django 5.0.6 on 2024-05-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0002_cfop_description_cfop_operation_alter_cfop_cfop'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcmsCst',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
