# Generated by Django 5.0.6 on 2024-05-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0003_icmscst'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcmsAliquota',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
