# Generated by Django 5.0.6 on 2024-05-31 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0005_icmsaliquotareduzida'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBENEF',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('icms_cst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impostos.icmscst')),
            ],
        ),
    ]
