# Generated by Django 5.0.6 on 2024-05-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0007_protege'),
    ]

    operations = [
        migrations.CreateModel(
            name='PisCofinsCst',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('aliquota', models.FloatField()),
            ],
        ),
    ]
