# Generated by Django 5.0.6 on 2024-05-31 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0008_piscofinscst'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturezaReceita',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('ncm', models.CharField(blank=True, max_length=8, null=True)),
                ('piscofins_cst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impostos.piscofinscst')),
            ],
        ),
    ]
