# Generated by Django 5.0.6 on 2024-05-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0009_naturezareceita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturezareceita',
            name='description',
            field=models.TextField(),
        ),
    ]
