# Generated by Django 5.0.6 on 2024-05-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0010_alter_naturezareceita_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturezareceita',
            name='ncm',
            field=models.TextField(blank=True, null=True),
        ),
    ]
