# Generated by Django 5.0.6 on 2024-06-01 14:55

import impostos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0011_alter_naturezareceita_ncm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfop',
            name='id',
        ),
        migrations.AlterField(
            model_name='cfop',
            name='cfop',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[impostos.models.validate_cfop]),
        ),
    ]
