# Generated by Django 5.0.6 on 2024-06-04 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0014_auto_recreate_table_naturezareceita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturezareceita',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='naturezareceita',
            name='piscofins_cst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impostos.piscofinscst'),
        ),
    ]
