# Generated by Django 5.0.6 on 2024-06-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0015_alter_naturezareceita_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbenef',
            name='legislation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
