# Generated by Django 5.0.6 on 2024-09-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0016_cbenef_legislation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturezareceita',
            name='category',
            field=models.CharField(blank=True, choices=[('Substituição Tributária', 'Substituição Tributária'), ('Alíquota Zero', 'Alíquota Zero'), ('Monofásico', 'Monofásico'), ('Suspensão', 'Suspensão')], max_length=255, null=True),
        ),
    ]
