# Generated by Django 5.0.6 on 2025-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0017_alter_naturezareceita_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscofinscst',
            name='type_company',
            field=models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Lucro Presumido'), ('3', 'Lucro Real')], default='3', max_length=1),
        ),
    ]
