# Generated by Django 5.0.6 on 2025-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0018_piscofinscst_type_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscofinscst',
            name='cofins_aliquota_company_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='piscofinscst',
            name='pis_aliquota_company_2',
            field=models.FloatField(default=0),
        ),
    ]
