# Generated by Django 5.0.6 on 2025-07-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0019_piscofinscst_cofins_aliquota_company_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icmsaliquotareduzida',
            name='code',
            field=models.DecimalField(decimal_places=2, max_digits=5, primary_key=True, serialize=False),
        ),
    ]
