# Generated by Django 5.0.6 on 2025-09-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0020_alter_icmsaliquotareduzida_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReformaTributaria',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('c_class_trib', models.CharField(blank=True, max_length=20, null=True)),
                ('aliquota_ibs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aliquota_cbs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description_c_class_trib', models.TextField(blank=True, null=True)),
                ('text_ec', models.CharField(blank=True, max_length=100, null=True)),
                ('text_lc', models.TextField(blank=True, null=True)),
                ('p_red_aliq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
