# Generated by Django 5.0.6 on 2025-09-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0021_reformatributaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reformatributaria',
            old_name='code',
            new_name='cst_ibs_cbs',
        ),
    ]
