# Generated by Django 5.0.6 on 2025-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0022_rename_code_reformatributaria_cst_ibs_cbs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reformatributaria',
            old_name='p_red_aliq',
            new_name='p_red_aliq_cbs',
        ),
        migrations.RemoveField(
            model_name='reformatributaria',
            name='description',
        ),
        migrations.AddField(
            model_name='reformatributaria',
            name='description_cst_ibs_cbs',
            field=models.CharField(blank=True, help_text='Descrição do Código de Situação Tributária do IBS e da CBS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reformatributaria',
            name='name_c_class_trib',
            field=models.CharField(blank=True, help_text='Nome da Classificação Tributária do IBS e da CBS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reformatributaria',
            name='p_red_aliq_ibs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reformatributaria',
            name='tipo_aliquota',
            field=models.CharField(blank=True, help_text='Define o tipo de alíquota aplicável, conforme disposto na Lei Complementar', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reformatributaria',
            name='c_class_trib',
            field=models.CharField(blank=True, help_text='Classificação Tributária do IBS e da CBS, sendo os três primeiros dígitos idênticos ao CST-IBS/CBS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reformatributaria',
            name='cst_ibs_cbs',
            field=models.CharField(help_text='Código de Situação Tributária do IBS e da CBS', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reformatributaria',
            name='description_c_class_trib',
            field=models.TextField(blank=True, help_text='Descrição da Classificação Tributária do IBS e da CBS', null=True),
        ),
    ]
