# Generated by Django 5.0.6 on 2025-09-27 18:06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0023_rename_p_red_aliq_reformatributaria_p_red_aliq_cbs_and_more'),
    ]

    operations = [
        # 1. Remove a Primary Key de 'cst_ibs_cbs'
        migrations.AlterField(
            model_name='reformatributaria',
            name='cst_ibs_cbs',
            field=models.CharField(max_length=10, help_text='Código de Situação Tributária do IBS e da CBS', unique=True),
        ),

        # 2. Adiciona o novo campo 'id' (será a nova PK)
        migrations.AddField(
            model_name='reformatributaria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),        
    ]
