# Generated by Django 5.0.6 on 2025-09-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0024_auto_20250927_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reformatributaria',
            name='cst_ibs_cbs',
            field=models.CharField(help_text='Código de Situação Tributária do IBS e da CBS', max_length=10),
        ),
    ]
