# Generated by Django 5.0.6 on 2024-05-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('id_estado', models.IntegerField()),
                ('ibge', models.CharField(max_length=8)),
                ('nome_estado', models.CharField(max_length=64)),
                ('uf_estado', models.CharField(max_length=2)),
            ],
        ),
    ]
