# Generated by Django 5.0.6 on 2024-05-25 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('erp', '0002_rename_erpmodel_erp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('num_stores', models.IntegerField()),
                ('date_contract', models.DateField()),
                ('date_send', models.DateField()),
                ('economic_benefit', models.BooleanField(verbose_name='Benefício Econômico')),
                ('accounting_name', models.CharField(max_length=255, verbose_name='Nome Contabilidade')),
                ('commercial_responsible', models.CharField(max_length=255, verbose_name='Responsável Comercial')),
                ('owner', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('erp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.erp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
