# Generated by Django 5.0.6 on 2024-06-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0001_initial'),
        ('clients', '0003_client_is_active_store'),
        ('erp', '0002_rename_erpmodel_erp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='accounting_name',
        ),
        migrations.AddField(
            model_name='client',
            name='accounting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='accountings.accounting', verbose_name='Contabilidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='day_sent',
            field=models.CharField(blank=True, choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='erp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='erp.erp'),
        ),
    ]
