# Generated by Django 5.0.6 on 2024-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_accounting_name_client_accounting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_load_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Primeira Carga'),
        ),
    ]
