# Generated by Django 5.0.6 on 2024-06-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_first_load_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='day_sent',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30')], max_length=2, null=True),
        ),
    ]
