# Generated by Django 5.0.6 on 2024-06-26 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_store_created_at_store_updated_at_store_user_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client')),
            ],
        ),
    ]
