# Generated by Django 5.0.6 on 2024-07-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_rename_result_logintegration_result_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='password_route',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Senha do usuário'),
        ),
        migrations.AddField(
            model_name='store',
            name='port_route',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Porta'),
        ),
        migrations.AddField(
            model_name='store',
            name='user_route',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Usuário para conectar'),
        ),
    ]
