# Generated by Django 5.0.6 on 2024-07-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_connection_route_client_password_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='database_route',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Senha do usuário'),
        ),
    ]
