# Generated by Django 5.0.6 on 2024-07-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_database_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18, null=True, verbose_name='CNPJ'),
        ),
    ]
