# Generated by Django 5.0.6 on 2024-08-07 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_client_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
