# Generated by Django 5.0.6 on 2024-08-08 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_client_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
