# Generated by Django 5.0.6 on 2025-03-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_client_date_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_status',
            field=models.CharField(blank=True, choices=[('1', 'Ativo'), ('2', 'Inativo'), ('3', 'Suspenso')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_date_get',
            field=models.DateField(blank=True, null=True, verbose_name='Último Recebimento'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_date_send',
            field=models.DateField(blank=True, null=True, verbose_name='Último Envio'),
        ),
        migrations.AddField(
            model_name='logintegration',
            name='integration_choice',
            field=models.CharField(blank=True, choices=[('1', 'Dados Recebidos'), ('2', 'Dados Enviados')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='logintegration',
            name='method_integration',
            field=models.CharField(blank=True, choices=[('1', 'API'), ('2', 'FTP'), ('3', 'SFTP'), ('4', 'Manual')], max_length=2, null=True),
        ),
    ]
