# Generated by Django 5.0.6 on 2025-03-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_client_client_status_client_last_date_get_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintegration',
            old_name='integration_choice',
            new_name='data_option',
        ),
    ]
