# Generated by Django 5.0.6 on 2025-03-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_rename_integration_choice_logintegration_data_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='method_integration',
            field=models.CharField(blank=True, choices=[('1', 'API'), ('2', 'FTP'), ('3', 'SFTP'), ('4', 'Manual')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.CharField(blank=True, choices=[('1', 'Ativo'), ('2', 'Inativo'), ('3', 'Suspenso')], default=1, max_length=2, null=True),
        ),
    ]
