# Generated by Django 5.0.6 on 2025-03-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_client_method_integration_alter_client_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_date_get',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Recebimento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_date_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Envio'),
        ),
    ]
