# Generated by Django 5.0.6 on 2025-04-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_syncing'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncing',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
