# Generated by Django 5.0.6 on 2025-04-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_syncing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_company',
            field=models.CharField(blank=True, choices=[('1', 'Simples Nacional'), ('2', 'Lucro Presumido'), ('3', 'Lucro Real')], default=3, max_length=2, null=True),
        ),
    ]
