# Generated by Django 5.0.6 on 2025-07-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_client_type_company'),
        ('erp', '0008_erp_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='periodicity_exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.erpintegrationschedule'),
        ),
    ]
