# Generated by Django 5.0.6 on 2025-06-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_manager_profile_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cattle_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pricing_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_simulation_permission',
            field=models.BooleanField(default=False),
        ),
    ]
