# Generated by Django 5.0.6 on 2025-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_cattle_permission_profile_pricing_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tax_management_permission',
            field=models.BooleanField(default=False),
        ),
    ]
