# Generated by Django 5.0.6 on 2024-06-04 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_is_active_store'),
        ('impostos', '0015_alter_naturezareceita_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('barcode', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('ncm', models.CharField(max_length=8)),
                ('cest', models.CharField(blank=True, max_length=7, null=True)),
                ('pis_aliquota', models.FloatField()),
                ('cofins_aliquota', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_pending_sync', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cbenef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impostos.cbenef')),
                ('cfop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impostos.cfop')),
                ('cofins_cst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofins_cst_items', to='impostos.piscofinscst')),
                ('icms_aliquota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impostos.icmsaliquota')),
                ('icms_aliquota_reduzida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impostos.icmsaliquotareduzida')),
                ('icms_cst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impostos.icmscst')),
                ('naturezareceita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='impostos.naturezareceita')),
                ('pis_cst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pis_cst_items', to='impostos.piscofinscst')),
                ('protege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impostos.protege')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.store')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='unique_store_code'),
        ),
    ]
