# Generated by Django 5.0.6 on 2024-06-04 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_day_sent'),
        ('impostos', '0015_alter_naturezareceita_id_and_more'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cofins_cst',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pis_cst',
        ),
        migrations.AddField(
            model_name='item',
            name='piscofins_cst',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='piscofins_cst_items', to='impostos.piscofinscst'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='cbenef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='impostos.cbenef'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cfop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='impostos.cfop'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icms_aliquota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='impostos.icmsaliquota'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icms_aliquota_reduzida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='impostos.icmsaliquotareduzida'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icms_cst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='impostos.icmscst'),
        ),
        migrations.AlterField(
            model_name='item',
            name='protege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='impostos.protege'),
        ),
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.store'),
        ),
    ]
