# Generated by Django 5.0.6 on 2024-06-06 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_day_sent'),
        ('items', '0002_remove_item_cofins_cst_remove_item_pis_cst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
        migrations.AddField(
            model_name='item',
            name='client',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, to='clients.client'),
            preserve_default=False,
        ),
    ]
