# Generated by Django 5.0.6 on 2024-06-06 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_day_sent'),
        ('items', '0003_remove_item_store_item_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, to='clients.store'),
            preserve_default=False,
        ),
    ]
