# Generated by Django 5.0.6 on 2024-06-06 22:18

from django.db import migrations

def copy_store_to_client(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    for item in Item.objects.all():
        item.client = item.store.client
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_store'),
    ]

    operations = [
        migrations.RunPython(copy_store_to_client),
    ]
