# Generated by Django 5.0.6 on 2024-06-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_copy_store_to_client'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=['store', 'code'], name='unique_store_code'),
        ),
    ]
