# Generated by Django 5.0.6 on 2024-06-07 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0016_cbenef_legislation'),
        ('items', '0007_remove_item_unique_store_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cbenef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='impostos.cbenef'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icms_aliquota_reduzida',
            field=models.CharField(max_length=3),
        ),
    ]
