# Generated by Django 5.0.6 on 2024-06-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_item_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cest',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
    ]
