# Generated by Django 5.0.6 on 2024-06-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_item_barcode_alter_item_cest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='other_information',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='type_product',
            field=models.CharField(blank=True, choices=[('', '----'), ('Revenda', 'Revenda'), ('Imobilizado', 'Imobilizado'), ('Insumos', 'Insumos')], default='', max_length=20),
        ),
    ]
