# Generated by Django 5.0.6 on 2024-06-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_item_other_information_item_type_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='other_information',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
