# Generated by Django 5.0.6 on 2024-06-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_item_other_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status_item',
            field=models.IntegerField(choices=[(0, 'Produto Novo'), (1, 'Problemas Encontrados'), (2, 'Aguardando Sincronização'), (3, 'Validado')], default=1),
        ),
    ]
