# Generated by Django 5.0.6 on 2024-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_item_status_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='history',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
