# Generated by Django 5.0.6 on 2024-06-24 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_store_created_at_store_updated_at_store_user_created_and_more'),
        ('items', '0015_item_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('barcode', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('ncm', models.CharField(max_length=255)),
                ('cest', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cfop', models.PositiveIntegerField()),
                ('icms_cst', models.IntegerField()),
                ('icms_aliquota', models.IntegerField()),
                ('icms_aliquota_reduzida', models.IntegerField()),
                ('protege', models.IntegerField()),
                ('cbenef', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('piscofins_cst', models.IntegerField()),
                ('pis_aliquota', models.FloatField()),
                ('cofins_aliquota', models.FloatField()),
                ('naturezareceita', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client')),
            ],
        ),
    ]
