# Generated by Django 5.0.6 on 2024-06-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_importeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeditem',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_item',
            field=models.IntegerField(choices=[(0, 'Produto Novo'), (1, 'Problemas Encontrados'), (2, 'Aguardando Sincronização'), (3, 'Validado')], default=3),
        ),
    ]
