# Generated by Django 5.0.6 on 2024-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_importeditem_is_pending_alter_item_status_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeditem',
            name='status_item',
            field=models.IntegerField(choices=[(0, 'Produto Novo'), (1, 'Problemas Encontrados')], default=1),
        ),
    ]
