# Generated by Django 5.0.6 on 2024-07-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_importeditem_status_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeditem',
            name='estado_destino',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='importeditem',
            name='estado_origem',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='importeditem',
            name='sequencial',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='estado_destino',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='estado_origem',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sequencial',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
