# Generated by Django 5.0.6 on 2024-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_importeditem_estado_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeditem',
            name='code',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
