# Generated by Django 5.0.6 on 2024-07-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_item_sync_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status_item',
            field=models.IntegerField(choices=[(0, 'Produto Novo'), (1, 'Integrado - Aguard Validação'), (2, 'Aguardando Sincronização'), (3, 'Validado')], default=3),
        ),
    ]
