# Generated by Django 5.0.6 on 2024-07-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_alter_item_status_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status_item',
            field=models.IntegerField(choices=[(0, 'Produto Novo'), (1, 'Aguardando Sincronização'), (2, 'Enviado - Aguard Validação'), (3, 'Validado')], default=3),
        ),
    ]
