# Generated by Django 5.0.6 on 2024-07-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_alter_item_status_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='await_sync_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
