# Generated by Django 5.0.6 on 2024-07-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_item_sync_validate_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeditem',
            name='divergent_columns',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
