# Generated by Django 5.0.6 on 2024-07-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_importeditem_divergent_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='await_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sync_validate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
