# Generated by Django 5.0.6 on 2024-08-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_alter_item_await_sync_at_alter_item_sync_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeditem',
            name='cfop',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importeditem',
            name='cofins_aliquota',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importeditem',
            name='icms_aliquota',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importeditem',
            name='icms_aliquota_reduzida',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importeditem',
            name='icms_cst',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importeditem',
            name='naturezareceita',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importeditem',
            name='pis_aliquota',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importeditem',
            name='piscofins_cst',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importeditem',
            name='protege',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
