# Generated by Django 5.0.6 on 2024-10-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_alter_importeditem_cfop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status_item',
            field=models.IntegerField(choices=[(0, 'Produto Novo'), (1, 'Aguardando Sincronização'), (2, 'Enviado - Aguard Validação'), (3, 'Validado'), (4, 'Inativo')], default=3),
        ),
    ]
