# Generated by Django 5.0.6 on 2024-12-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0030_alter_item_status_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeditem',
            name='icms_aliquota',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importeditem',
            name='icms_aliquota_reduzida',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
