# Generated by Django 5.0.6 on 2024-12-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0031_alter_importeditem_icms_aliquota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeditem',
            name='icms_aliquota',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importeditem',
            name='icms_aliquota_reduzida',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
