# Generated by Django 5.0.6 on 2025-05-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_client_type_company'),
        ('items', '0032_alter_importeditem_icms_aliquota_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importeditem',
            unique_together={('client', 'code')},
        ),
    ]
