# Generated by Django 5.0.6 on 2025-06-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0033_importeditem_percentual_reducao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importeditem',
            old_name='percentual_reducao',
            new_name='percentual_redbcde',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='percentual_reducao',
            new_name='percentual_redbcde',
        ),
    ]
