# Generated by Django 5.0.6 on 2025-07-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_rename_percentual_reducao_importeditem_percentual_redbcde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeditem',
            name='icms_aliquota_reduzida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='icms_aliquota_reduzida',
            field=models.CharField(max_length=5),
        ),
    ]
