# Generated by Django 5.0.6 on 2025-09-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0035_alter_importeditem_icms_aliquota_reduzida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeditem',
            name='aliquota_cbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='importeditem',
            name='aliquota_ibs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='importeditem',
            name='c_class_trib',
            field=models.CharField(blank=True, help_text='Classificação Tributária do IBS e da CBS, sendo os três primeiros dígitos idênticos ao CST-IBS/CBS', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='importeditem',
            name='cst_ibs_cbs',
            field=models.CharField(blank=True, help_text='Código de Situação Tributária do IBS e da CBS', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='importeditem',
            name='p_red_aliq_cbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='importeditem',
            name='p_red_aliq_ibs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
