# Generated by Django 5.0.6 on 2025-09-27 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostos', '0025_alter_reformatributaria_cst_ibs_cbs'),
        ('items', '0036_importeditem_aliquota_cbs_importeditem_aliquota_ibs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reforma_tributaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='impostos.reformatributaria'),
        ),
    ]
