# Generated by Django 5.0.6 on 2025-09-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0038_item_aliquota_cbs_item_aliquota_ibs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reforma_tributaria',
        ),
    ]
