# Generated by Django 5.0.6 on 2025-06-20 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricequote',
            old_name='description',
            new_name='product_description',
        ),
        migrations.AddField(
            model_name='pricequote',
            name='simulation_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Simulation Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricequote',
            name='product_price_01',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricequote',
            name='product_price_02',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
