# Generated by Django 5.0.6 on 2025-06-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsim', '0002_rename_description_pricequote_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricequote',
            name='icms_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricequote',
            name='interstate_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pricequote',
            name='pis_cofins_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricequote',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
