# Generated by Django 5.0.6 on 2025-07-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsim', '0003_alter_pricequote_icms_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricequote',
            name='tax_icms_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pricequote',
            name='product_icms_7',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is product taxed at 7% ICMS?'),
        ),
    ]
