# Generated by Django 5.0.6 on 2025-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsim', '0004_pricequote_tax_icms_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='only_shop_simulation',
            field=models.BooleanField(default=True, verbose_name='Only Shop Simulation'),
        ),
    ]
