# Generated by Django 5.0.6 on 2025-07-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsim', '0005_supplierprofile_only_shop_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricequote',
            name='product_imported',
            field=models.BooleanField(default=0, verbose_name='Is product imported?'),
            preserve_default=False,
        ),
    ]
