# Generated by Django 5.0.6 on 2024-07-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly')], default='D', max_length=1),
        ),
    ]
