# Generated by Django 5.0.6 on 2024-07-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_days_of_week_task_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('D', 'Diariamente'), ('W', 'Semanalmente')], default='D', max_length=1),
        ),
    ]
