# Generated by Django 5.0.6 on 2025-06-11 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('field_label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatrixSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cow_weighing_location', models.CharField(max_length=50)),
                ('monthly_sales_volume_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('average_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sales_per_month', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mean_weight_per_cow_producer_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mean_weight_per_cow_slaughterhouse_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mean_weight_per_cow_producer_arroba', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mean_weight_per_cow_slaughterhouse_arroba', models.DecimalField(decimal_places=2, max_digits=8)),
                ('yield_live_cow_pasture_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yield_butchered_cow_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_arroba_producer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_arroba_slaughterhouse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg_butchered_cow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slaughter_service_per_cow_producer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slaughter_service_per_cow_slaughterhouse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icms_debit_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('icms_credit_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('granted_credit_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('icms_loss_reversal_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protege_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fundeinfra_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cattles.fieldconfiguration')),
            ],
            options={
                'unique_together': {('field', 'value')},
            },
        ),
    ]
