# Generated by Django 5.0.6 on 2025-06-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixsimulation',
            name='cows_per_month_producer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='matrixsimulation',
            name='cows_per_month_slaughterhouse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='matrixsimulation',
            name='cows_per_week_producer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='matrixsimulation',
            name='cows_per_week_slaughterhouse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
