# Generated by Django 5.0.6 on 2025-06-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0002_matrixsimulation_cows_per_month_producer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrixsimulation',
            old_name='yield_butchered_cow_percent',
            new_name='yield_butchered_cow_producer_percent',
        ),
        migrations.RenameField(
            model_name='matrixsimulation',
            old_name='yield_live_cow_pasture_percent',
            new_name='yield_butchered_cow_slaughterhouse_percent',
        ),
        migrations.AddField(
            model_name='matrixsimulation',
            name='yield_live_cow_pasture_producer_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrixsimulation',
            name='yield_live_cow_pasture_slaughterhouse_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
