# Generated by Django 5.0.6 on 2025-06-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0004_rename_price_per_arroba_producer_matrixsimulation_price_closed_per_arroba_producer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixsimulation',
            name='commission_buyer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matrixsimulation',
            name='profit_gain_comparison',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='matrixsimulation',
            name='total_slaughter_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matrixsimulation',
            name='total_value_producer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='matrixsimulation',
            name='total_value_slaughterhouse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
