# Generated by Django 5.0.6 on 2025-06-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0005_matrixsimulation_commission_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrixsimulation',
            name='fundeinfra_percent',
        ),
        migrations.RemoveField(
            model_name='matrixsimulation',
            name='granted_credit_percent',
        ),
        migrations.RemoveField(
            model_name='matrixsimulation',
            name='icms_credit_percent',
        ),
        migrations.RemoveField(
            model_name='matrixsimulation',
            name='icms_debit_percent',
        ),
        migrations.RemoveField(
            model_name='matrixsimulation',
            name='icms_loss_reversal_percent',
        ),
        migrations.RemoveField(
            model_name='matrixsimulation',
            name='protege_percent',
        ),
    ]
