# Generated by Django 5.0.6 on 2025-06-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0006_remove_matrixsimulation_fundeinfra_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixsimulation',
            name='mean_weight_per_cow_producer_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='price_closed_per_arroba_slaughterhouse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='price_net_per_arroba_producer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='price_net_per_arroba_slaughterhouse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='price_per_kg_after_butchered_cow_producer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='price_per_kg_after_butchered_cow_slaughterhouse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='price_per_kg_butchered_cow_producer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='slaughter_service_per_cow_producer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='slaughter_service_per_cow_slaughterhouse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='total_sales_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='yield_butchered_cow_slaughterhouse_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='yield_live_cow_pasture_slaughterhouse_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
