# Generated by Django 5.0.6 on 2025-06-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0007_alter_matrixsimulation_mean_weight_per_cow_producer_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixsimulation',
            name='mean_weight_per_cow_producer_arroba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='matrixsimulation',
            name='mean_weight_per_cow_slaughterhouse_arroba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
