# Generated by Django 5.0.6 on 2025-06-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0009_butcherymaster_meatcut_usermeatcut_butcherydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butcherymaster',
            name='arroba_price_nf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='butcherymaster',
            name='cost_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='butcherymaster',
            name='invoice_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
