# Generated by Django 5.0.6 on 2025-06-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0010_alter_butcherymaster_arroba_price_nf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeatcut',
            name='meat_cut',
            field=models.CharField(max_length=100),
        ),
    ]
