# Generated by Django 5.0.6 on 2025-06-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0011_alter_usermeatcut_meat_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='butcherydetail',
            name='butchery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cattles.butcherymaster'),
            preserve_default=False,
        ),
    ]
