# Generated by Django 5.0.6 on 2025-06-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0012_butcherydetail_butchery'),
    ]

    operations = [
        migrations.AddField(
            model_name='butcherydetail',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
