# Generated by Django 5.0.6 on 2025-06-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0013_butcherydetail_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='butcherydetail',
            name='cut_class',
            field=models.CharField(choices=[('1A', '1ª'), ('2A', '2ª')], default='1A', max_length=2),
        ),
    ]
