# Generated by Django 5.0.6 on 2025-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattles', '0014_butcherydetail_cut_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixsimulation',
            name='is_estorno_icms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matrixsimulation',
            name='percent_comission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
