# Generated by Django 5.0.6 on 2025-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='State Code')),
                ('name', models.CharField(max_length=100, verbose_name='State Name')),
                ('aliquota_inter', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Interstate Rate')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
    ]
