# Generated by Django 5.0.6 on 2025-07-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_costs_created_at_costs_updated_at_states_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='cofins_aliquota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Interstate Rate'),
        ),
        migrations.AddField(
            model_name='states',
            name='pis_aliquota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Interstate Rate'),
        ),
    ]
