# Generated by Django 5.0.6 on 2025-05-22 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('message', models.TextField(max_length=500, verbose_name='Mensagem')),
                ('notification_type', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('danger', 'Urgente'), ('success', 'Sucesso'), ('system', 'Sistema')], default='info', max_length=20, verbose_name='Tipo')),
                ('action_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de ação')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('icon', models.CharField(default='fa fa-bell', max_length=50, verbose_name='Ícone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
