name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # branch para monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3      

    - name: Setup SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'github.com'

    - name: Configure Git
      run: |
        git config --global user.email "fernando.rorato@gmail.com"
        git config --global user.name "Fernando Rorato"
        git remote set-url origin git@github.com:fndrorato/oriontax-integrador-cicd.git

    - name: Deploy to DigitalOcean Droplet
      run: |
        ssh -o StrictHostKeyChecking=no root@174.138.73.68 <<EOF
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        cd /var/www/orion-ci-cd &&
        git pull origin main &&
        source venv/bin/activate &&  # Se você estiver usando um virtualenv
        pip install -r requirements.txt &&
        systemctl restart gunicorn-orion_ci_cd.service  # Substitua pelo seu serviço real
        EOF
