# Generated by Django 5.0.6 on 2024-11-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nNF', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=10)),
                ('tpNF', models.IntegerField()),
                ('cUF', models.IntegerField()),
                ('cNF', models.CharField(max_length=10)),
                ('natOp', models.CharField(max_length=100)),
                ('mod', models.CharField(max_length=10)),
                ('cMunFG', models.IntegerField()),
                ('tpAmb', models.IntegerField()),
                ('dhEmi', models.DateTimeField()),
                ('CNPJ', models.CharField(max_length=14)),
                ('xNome', models.CharField(max_length=200)),
                ('xFant', models.CharField(blank=True, max_length=200, null=True)),
                ('IE', models.CharField(blank=True, max_length=20, null=True)),
                ('CRT', models.IntegerField()),
                ('cMun', models.IntegerField()),
                ('xMun', models.CharField(max_length=100)),
                ('UF', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'unique_together': {('nNF', 'serie', 'tpNF')},
            },
        ),
    ]
