# Generated by Django 5.0.6 on 2025-03-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespedido',
            name='CEP_Destinatario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salespedido',
            name='UF_Destinatario',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='salespedido',
            name='cMun_Destinatario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salespedido',
            name='dhSaiEnt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salespedido',
            name='indIEDestinatario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salespedido',
            name='nro_Destinatario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salespedido',
            name='xBairro_Destinatario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salespedido',
            name='xLgr_Destinatario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salespedido',
            name='xMun_Destinatario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salespedido',
            name='xNome_Destinatario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
