# Generated by Django 5.0.6 on 2024-11-02 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_NumItem', models.IntegerField()),
                ('cProd', models.CharField(max_length=20)),
                ('cEAN', models.CharField(blank=True, max_length=13, null=True)),
                ('xProd', models.CharField(max_length=200)),
                ('NCM', models.CharField(max_length=8)),
                ('CEST', models.CharField(blank=True, max_length=7, null=True)),
                ('CFOP', models.CharField(max_length=4)),
                ('uCom', models.CharField(max_length=6)),
                ('qCom', models.DecimalField(decimal_places=4, max_digits=15)),
                ('vUnCom', models.DecimalField(decimal_places=4, max_digits=15)),
                ('vProd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cEANTrib', models.CharField(blank=True, max_length=13, null=True)),
                ('uTrib', models.CharField(max_length=6)),
                ('qTrib', models.DecimalField(decimal_places=4, max_digits=15)),
                ('vUnTrib', models.DecimalField(decimal_places=4, max_digits=15)),
                ('indTot', models.IntegerField()),
                ('ICMS_orig', models.IntegerField()),
                ('ICMS_CST', models.IntegerField()),
                ('ICMS_modBC', models.IntegerField()),
                ('ICMS_vBC', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ICMS_pICMS', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ICMS_vICMS', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PIS_CST', models.IntegerField()),
                ('PIS_vBC', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PIS_pPIS', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PIS_vPIS', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PIS_PISAliq', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('COFINS_CST', models.IntegerField()),
                ('COFINS_vBC', models.DecimalField(decimal_places=2, max_digits=15)),
                ('COFINS_pCOFINS', models.DecimalField(decimal_places=2, max_digits=5)),
                ('COFINS_vCOFINS', models.DecimalField(decimal_places=2, max_digits=15)),
                ('COFINS_COFINSAliq', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prod_cBenef', models.CharField(blank=True, max_length=20, null=True)),
                ('ICMS_pRedBC', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PIS_PISNT', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('COFINS_COFINSNT', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sales_cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.salescab')),
            ],
            options={
                'unique_together': {('sales_cab', 'prod_NumItem')},
            },
        ),
    ]
