# Generated by Django 5.0.6 on 2025-03-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salespedido_cep_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetalhe',
            name='vICMSDeson',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
