# Generated by Django 5.0.6 on 2024-11-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salescab_created_at_salescab_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salescab',
            unique_together={('CNPJ', 'nNF', 'serie', 'tpNF')},
        ),
        migrations.AlterField(
            model_name='salescab',
            name='cMun',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salescab',
            name='cMunFG',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
