# Generated by Django 5.0.6 on 2024-11-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salescab_unique_together_alter_salescab_cmun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdet',
            name='item_validado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdet',
            name='validado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
