# Generated by Django 5.0.6 on 2024-11-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesdet_item_validado_salesdet_validado_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdet',
            name='ICMS_modBC',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
