# Generated by Django 5.0.6 on 2025-03-31 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_tpamb_salespedido_tpamb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salespedido',
            old_name='tpamb',
            new_name='tpAmb',
        ),
    ]
