# Generated by Django 5.0.6 on 2024-11-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_salesdet_cest_alter_salesdet_cean_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file_name', models.CharField(max_length=255)),
                ('log', models.TextField()),
                ('resultado', models.BooleanField()),
                ('data_hora_criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
