# Generated by Django 5.0.6 on 2024-11-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_client_date_send'),
        ('items', '0030_alter_item_status_item'),
        ('sales', '0008_fileprocessinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescab',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='clients.client'),
        ),
        migrations.AddField(
            model_name='salesdet',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='salesdet',
            name='motivo_valicadao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
